app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', 'AppController@index');
Route::get('/create', 'AppController@createSimulation');
Route::post('/add', 'AppController@store');
// Route::post('auth/facebookLogin/{offline?}', 'Auth\AuthController@facebookLogin');
// Route::post('signup', 'AppController@signup');

Route::group(['namespace' => 'Admin', 'prefix' => 'admin'], function() {
    Route::auth();
    Route::get('/', 'AdminController@dashboard');
    //Route::get('/form', 'AdminController@form');
    Route::get('/list', 'AdminController@pagination');
    Route::get('/tamouil_sayara', 'AdminController@tamouil_sayara');
    Route::get('/tamouil_moueddet_ennakl', 'AdminController@tamouil_moueddet_ennakl');
    Route::get('/tamouil_akkarat_afrad', 'AdminController@tamouil_akkarat_afrad');
    Route::get('/tamouil_mochtarayet', 'AdminController@tamouil_mochtarayet');
    Route::get('/tamouil_menzel', 'AdminController@tamouil_menzel');

    Route::get('/print/{date_deb}/{date_fin}', 'AdminController@printcsv');

    //Route::post('/store', 'ParticipantController@store');
    Route::get('/show/{id}', 'AdminController@edit');
    Route::post('/update/{id}', 'AdminController@update');
    Route::get('/delete/{id}', 'AdminController@destroy');
});

app/Member.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Member extends Model
{
    //
    public function getFullNameAttribute(){
        return $this->attributes['name'].' '.$this->attributes['surname'] ;
    }
}

resources/views/admin/includes/footer.blade.php
<!-- footer content -->
<footer>
    <div class="pull-right">
        Starter Site Admin Template by Box.agency
    </div>
    <div class="clearfix"></div>
</footer>
</div>
</div>
<!-- /footer content -->

resources/views/admin/includes/sidebar.blade.php
<div class="col-md-3 left_col">
    <div class="left_col scroll-view">
        <div class="navbar nav_title" style="border: 0;">
            <a href="{{ url('admin/') }}" class="site_title"><i class="fa fa-gears"></i> <span>Administration</span></a>
        </div>
        <div class="clearfix"></div>

        <!-- menu profile quick info -->
        <div class="profile">
            <div class="profile_pic">
                <img src="{{ asset('images/user.png') }}" alt="..." class="img-circle profile_img">
            </div>
            <div class="profile_info">
                <span>Hello : </span>
                <h2>{{ Auth::user()->full_name }}</h2>
            </div>
        </div>
        <!-- /menu profile quick info -->
        <br />

        <!-- sidebar menu -->
        <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
            <div class="menu_section">
                <h3>General</h3>
                <ul class="nav side-menu">
                    <li><a><i class="fa fa-home"></i> Home Dashboard <span class="fa fa-chevron-down"></span></a>
                        <ul class="nav child_menu">
                            <li><a href="{{ url('admin/') }}"> Dashboard </a></li>
                            <li><a href="{{ url('admin/list') }}"> Listes Des Membres </a></li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
        <!-- /sidebar menu -->
    </div>
</div>

resources/views/admin/includes/topbar.blade.php
<!-- top navigation -->
<div class="top_nav">
    <div class="nav_menu">
        <nav>
            <div class="nav toggle">
                <a id="menu_toggle"><i class="fa fa-bars"></i></a>
            </div>
            <ul class="nav navbar-nav navbar-right">
                <li class="">
                    <a href="javascript:;" class="user-profile dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                        <img src="{{ asset('images/user.png') }}" alt="">
                        {{ Auth::user()->full_name }}
                        <span class=" fa fa-angle-down"></span>
                    </a>
                    <ul class="dropdown-menu dropdown-usermenu pull-right">
                        <li><a href="{{ url('/admin/logout') }}"><i class="fa fa-sign-out pull-right"></i> Log Out</a></li>
                    </ul>
                </li>
            </ul>
        </nav>
    </div>
</div>
<!-- /top navigation -->